"""Traceable deterministic research synthesis."""

from __future__ import annotations

from peos.domain.research.model import NormalizedClaim


def synthesis_body(
    claims: tuple[tuple[str, NormalizedClaim], ...],
    contradictions: tuple[tuple[str, str, str], ...],
    unreadable: int,
) -> str:
    supported = [
        (identifier, claim) for identifier, claim in claims if claim.evidence_status == "SUPPORTED"
    ]
    contested_by_key = {key: (positive, negative) for key, positive, negative in contradictions}
    direct = (
        "The evidence is contested."
        if contradictions
        else "; ".join(claim.proposition for _, claim in supported)
        or "No uncontested supported claim was extracted."
    )
    supported_text = (
        "\n".join(f"- [{identifier}] {claim.proposition}" for identifier, claim in supported)
        or "No uncontested supported claim was extracted."
    )
    lookup = {identifier: claim for identifier, claim in claims}
    contested_text = (
        "\n".join(
            f"- [{positive} vs {negative}] "
            f"{lookup[positive].proposition} | {lookup[negative].proposition}"
            for _, (positive, negative) in sorted(contested_by_key.items())
        )
        or "No contested claim was extracted."
    )
    open_question = (
        "Review the unreadable source segments before treating the synthesis as complete."
        if unreadable
        else "No additional question was generated by the deterministic vertical slice."
    )
    return (
        f"# Direct answer\n\n{direct}\n\n"
        f"# Supported claims\n\n{supported_text}\n\n"
        f"# Contested claims\n\n{contested_text}\n\n"
        "# Limitations\n\n"
        "- Deterministic mock extraction supports only the Milestone 4 line-claim grammar.\n"
        f"- {unreadable} unreadable source segment(s) were excluded.\n\n"
        f"# Open questions\n\n- {open_question}\n"
    )
