"""Durable run-journal storage contract."""

from __future__ import annotations

from typing import Protocol

from peos.domain.runs.model import Event


class RunRepository(Protocol):
    def create(self, manifest: dict[str, object], inputs: dict[str, object]) -> None: ...
    def read_manifest(self, run_id: str) -> dict[str, object]: ...
    def read_inputs(self, run_id: str) -> dict[str, object]: ...
    def events(self, run_id: str) -> list[Event]: ...
    def append(self, run_id: str, event: Event) -> None: ...
    def write_evidence(self, run_id: str, name: str, envelope: dict[str, object]) -> None: ...
    def read_evidence(self, run_id: str, name: str) -> dict[str, object]: ...
    def write_outputs(self, run_id: str, outputs: dict[str, object]) -> None: ...
    def read_outputs(self, run_id: str) -> dict[str, object] | None: ...
