"""Canonical immutable source-object storage contract."""

from typing import Protocol


class SourceObjectStore(Protocol):
    def put(self, raw: bytes) -> tuple[str, str]: ...
    def read(self, object_hash: str) -> bytes: ...
    def verify(self, object_hash: str) -> str: ...
    def exists(self, object_hash: str) -> bool: ...
