"""Pure construction for the deterministic mock-model workflow."""

import hashlib

from peos.domain.artifacts.model import Artifact, Author, Provenance
from peos.domain.artifacts.validation import validate_artifact
from peos.domain.workflows.model import StepDefinition, WorkflowDefinition

WORKFLOW = WorkflowDefinition(
    "sample.mock-summarize-concept",
    "1.0.0",
    (
        StepDefinition(1, "mock-summarize-concept", "1.0.0", "READ_ONLY", max_output_bytes=8192),
        StepDefinition(2, "commit-model-summary", "1.0.0", "REVERSIBLE_WRITE"),
    ),
)


def prepare_summary(
    source: Artifact, run_id: str, created_at: str, output: dict[str, object]
) -> Artifact:
    identifier = (
        "art_"
        + hashlib.sha256(
            f"{run_id}:sample.mock-summarize-concept:1.0.0:commit-model-summary".encode()
        ).hexdigest()[:32]
    )
    tags = list(source.tags)
    for tag in ("model-assisted", "mock-model"):
        if tag not in tags:
            tags.append(tag)
    artifact = Artifact(
        id=identifier,
        type="knowledge.concept",
        schema_version=1,
        title=str(output["title"]),
        status="draft",
        workspace_id=source.workspace_id,
        created_at=created_at,
        updated_at=created_at,
        authors=(Author("system", "peos"),),
        sensitivity=source.sensitivity,
        tags=tuple(tags),
        links=(),
        provenance=Provenance(
            "system",
            run_id,
            ({"artifact_id": source.id, "content_hash": source.content_hash},),
        ),
        content_hash=None,
        body=(
            "Model-assisted summary generated by deterministic mock provider.\n\n"
            + str(output["summary"])
        ),
    )
    return validate_artifact(
        artifact, expected_workspace_id=source.workspace_id, require_hash=False
    )
